vim.keymap.set('n', '<leader>eif', 'ggO/* eslint-disable */<esc> bi')
vim.keymap.set('n', '<leader>eil', 'O// eslint-disable-next-line ')
vim.keymap.set('n', '<leader>ef', ':EslintFixAll<cr>')
vim.keymap.set('n', '<leader>cl', '$v^xiconsole.log(<esc>pa)<esc>')
vim.keymap.set('n', '<leader>cl', '$v^xiconsole.log(<esc>pa)<esc>')
vim.keymap.set('n', '<leader>tgs', ':TypescriptGoToSourceDefinition<cr>')
